const CRAM_CLASSES = "CRAM_CLASSES";
const CRAM_CLASSES_SKIP_LECTURES = "CRAM_CLASSES_SKIP_LECTURES";
const AVOID_DAYS = "AVOID_DAYS";
const LONGEST_RUN = "LONGEST_RUN";
const AVOID_CLASHES = "AVOID_CLASHES";

export default {
  CRAM_CLASSES_SKIP_LECTURES,
  CRAM_CLASSES,
  AVOID_CLASHES,
  AVOID_DAYS,
  LONGEST_RUN
};
