export const CRAM_CLASSES = "CRAM_CLASSES";
export const CRAM_CLASSES_SKIP_LECTURES = "CRAM_CLASSES_SKIP_LECTURES";
export const AVOID_DAYS = "AVOID_DAYS";
export const LONGEST_RUN = "LONGEST_RUN";
export const AVOID_CLASHES = "AVOID_CLASHES";

export default {
  CRAM_CLASSES_SKIP_LECTURES,
  CRAM_CLASSES,
  AVOID_DAYS,
  LONGEST_RUN
};
