import { VIEW_SUBJECT, STOP_VIEWING_SUBJECT } from "../actionTypes";

const initialState = { viewing: true, subject: {
    "name":"Visualising Environments",
    "year":2019,
    "color":"#FEBF5D",
    "data":{
       "code":"ABPL10003",
       "period":"semester_2",
       "_classList":[
          {
             "description":"Lecture 1",
             "day":0,
             "start":10,
             "finish":11,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Mandatory",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/L01/01"
             ],
             "locations":[
                "PAR-Doug McDonell-309 (Denis Driscoll Theatrette)"
             ],
             "classCode":{
                "number":1,
                "type":"L"
             },
             "streamNumber":1
          },
          {
             "description":"Workshop 1",
             "day":0,
             "start":14.25,
             "finish":17.25,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/W01/01"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-120"
             ],
             "classCode":{
                "number":1,
                "type":"W"
             },
             "streamNumber":1
          },
          {
             "description":"Studio 1",
             "day":0,
             "start":14.25,
             "finish":17.25,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/ST1/01"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-240"
             ],
             "classCode":{
                "number":1,
                "type":"ST"
             },
             "streamNumber":1
          },
          {
             "description":"on hold",
             "day":1,
             "start":9,
             "finish":12,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/W01/02"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-120"
             ],
             "classCode":{
                "number":1,
                "type":"W"
             },
             "streamNumber":2
          },
          {
             "description":"on hold",
             "day":1,
             "start":17.25,
             "finish":20.25,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/ST1/03"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-213"
             ],
             "classCode":{
                "number":1,
                "type":"ST"
             },
             "streamNumber":3
          },
          {
             "description":"Studio 1",
             "day":1,
             "start":9,
             "finish":12,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/ST1/02"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-226"
             ],
             "classCode":{
                "number":1,
                "type":"ST"
             },
             "streamNumber":2
          },
          {
             "description":"Workshop 1",
             "day":1,
             "start":17.25,
             "finish":20.25,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/W01/03"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-246"
             ],
             "classCode":{
                "number":1,
                "type":"W"
             },
             "streamNumber":3
          }
       ],
       "_irregularClasses":[
 
       ],
       "_mandatoryClasses":[
          {
             "description":"Lecture 1",
             "day":0,
             "start":10,
             "finish":11,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Mandatory",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/L01/01"
             ],
             "locations":[
                "PAR-Doug McDonell-309 (Denis Driscoll Theatrette)"
             ],
             "classCode":{
                "number":1,
                "type":"L"
             },
             "streamNumber":1
          }
       ],
       "_regularClasses":[
          {
             "description":"Workshop 1",
             "day":0,
             "start":14.25,
             "finish":17.25,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/W01/01"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-120"
             ],
             "classCode":{
                "number":1,
                "type":"W"
             },
             "streamNumber":1
          },
          {
             "description":"Studio 1",
             "day":0,
             "start":14.25,
             "finish":17.25,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/ST1/01"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-240"
             ],
             "classCode":{
                "number":1,
                "type":"ST"
             },
             "streamNumber":1
          },
          {
             "description":"on hold",
             "day":1,
             "start":9,
             "finish":12,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/W01/02"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-120"
             ],
             "classCode":{
                "number":1,
                "type":"W"
             },
             "streamNumber":2
          },
          {
             "description":"Studio 1",
             "day":1,
             "start":9,
             "finish":12,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/ST1/02"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-226"
             ],
             "classCode":{
                "number":1,
                "type":"ST"
             },
             "streamNumber":2
          },
          {
             "description":"on hold",
             "day":1,
             "start":17.25,
             "finish":20.25,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/ST1/03"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-213"
             ],
             "classCode":{
                "number":1,
                "type":"ST"
             },
             "streamNumber":3
          },
          {
             "description":"Workshop 1",
             "day":1,
             "start":17.25,
             "finish":20.25,
             "weeks":[
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43
             ],
             "type":"Variable",
             "subjectCode":"ABPL10003",
             "codes":[
                "ABPL10003/U/1/SM2/W01/03"
             ],
             "locations":[
                "PAR-Glyn Davis (MSD)-246"
             ],
             "classCode":{
                "number":1,
                "type":"W"
             },
             "streamNumber":3
          }
       ],
       "_streamContainers":[
 
       ]
    },
    "error":null,
    "loading":false
 } };

export default (state = initialState, action) => {
  switch (action.type) {
    case VIEW_SUBJECT:
      return { ...state, viewing: true, subject: action.payload };
    case STOP_VIEWING_SUBJECT:
      return { ...state, viewing: false, subject: null };
    default:
      return { ...state };
  }
};
