export enum SubjectPeriod {
  Semester_1 = 'semester_1',
  Semester_2 = 'semester_2',
  Summer_Term = 'summer_term',
  Winter_Term = 'winter_term',
  January = 'january',
  February = 'february',
  March = 'march',
  April = 'april',
  May = 'may',
  June = 'june',
  July = 'july',
  August = 'august',
  September = 'september',
  October = 'october',
  November = 'november',
  December = 'december',
}
