// Subject List
export const FETCH_SUBJECT_LIST_BEGIN = "FETCH_SUBJECT_LIST_BEGIN";
export const FETCH_SUBJECT_LIST_SUCCESS = "FETCH_SUBJECT_LIST_SUCCESS";
export const FETCH_SUBJECT_LIST_FAILURE = "FETCH_SUBJECT_LIST_FAILURE";

// Subjects
export const GET_SUBJECT_BEGIN = "GET_SUBJECT_BEGIN";
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";
export const GET_SUBJECT_FAILURE = "GET_SUBJECT_FAILURE";
export const REMOVE_SUBJECT = "REMOVE_SUBJECT";

// Optimiser
export const BEGIN_OPTIMISATION = "BEGIN_OPTIMISATION";
export const COMPLETE_OPTIMISATION = "COMPLETE_OPTIMISATION";

// Timetables
export const NEXT_TIMETABLE = "NEXT_TIMETABLE";
export const PREVIOUS_TIMETABLE = "PREVIOUS_TIMETABLE";
