// Subject List
export const FETCH_SUBJECT_LIST_BEGIN = "FETCH_SUBJECT_LIST_BEGIN";
export const FETCH_SUBJECT_LIST_SUCCESS = "FETCH_SUBJECT_LIST_SUCCESS";
export const FETCH_SUBJECT_LIST_FAILURE = "FETCH_SUBJECT_LIST_FAILURE";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const REMOVE_SUBJECT = "REMOVE_SUBJECT";
